# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 476ddcfbab805f14a8c4dd837ea6951963457f2484e1ba0f6d44e0825715bfded7b6e0dd0b4effd24a6d19efd445d92b926b69119d460aac8062c4ae781f597a

test:
  secret_key_base: db5e45c052f63b092ddff5d9f0e2169afc7ca48a1d926ec6b9e2abfb5f64f264f8694e47d2ed6a85f9acdce750f7b25b1319f1f56f8bf9e9f840db75dd02909f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
